DELETE  http://localhost:3001/api/persons/67c775e85bf1f9df9da4070
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/67c767a46809b52bd376526f
###
GET http://localhost:3001/info
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "antMAN",
  "number": "040-22334455"
}

###
PUT http://localhost:3001/api/persons/67c767a46809b52bd376526f
Content-Type: application/json

{
  "name": "Ar",
  "number": "123"
}
